import type { Dictionary } from '@/lib/i18n/types'
import type { SurveyConfig } from '@/lib/onboarding/surveyConfig'

/**
 * Expert onboarding: **10 URL steps** (progress segments), inline fields only.
 * Sub-step `id`s inside `field_stack` stay stable — they key `onboardingState.answers`
 * and AI context builders.
 */
export function getExpertSurveyConfig(t: Dictionary): SurveyConfig {
  const o = t.onboarding
  return {
    steps: [
      {
        id: 'expert_welcome',
        type: 'static',
        title: o.welcomeTitle,
        subtitle: o.welcomeSubtitle,
        body: o.welcomeBody,
        helpText: o.welcomeHelp,
      },
      {
        id: 'profile_place',
        type: 'field_stack',
        title: o.stackProfileTitle,
        subtitle: o.stackProfileSubtitle,
        helpText: o.stackProfileHelp,
        fields: [
          {
            kind: 'text',
            id: 'display_name',
            title: o.displayNameTitle,
            placeholder: o.displayNamePlaceholder,
            mapsTo: 'profile.name',
            maxLength: 80,
          },
          {
            kind: 'country_select',
            id: 'country',
            title: o.countryTitle,
            placeholder: o.countryPlaceholder,
            mapsTo: 'profile.country',
          },
          {
            kind: 'text',
            id: 'city',
            title: o.cityTitle,
            placeholder: o.cityPlaceholder,
            mapsTo: 'profile.city',
            maxLength: 80,
          },
        ],
      },
      {
        id: 'life_money_basics',
        type: 'field_stack',
        title: o.stackLifeMoneyTitle,
        subtitle: o.stackLifeMoneySubtitle,
        helpText: o.stackLifeMoneyHelp,
        fields: [
          {
            kind: 'single_select',
            id: 'living_situation',
            title: o.livingTitle,
            mapsTo: 'onboarding.livingSituation',
            options: [
              { value: 'rent_alone', label: o.livingRentAlone },
              { value: 'rent_roommates', label: o.livingRentShared },
              { value: 'own_mortgage', label: o.livingMortgage },
              { value: 'own_outright', label: o.livingOwner },
              { value: 'with_parents', label: o.livingFamily },
              { value: 'other', label: o.livingOther },
            ],
          },
          {
            kind: 'single_select',
            id: 'relationship_status',
            title: o.relationshipTitle,
            mapsTo: 'onboarding.relationship',
            options: [
              { value: 'single', label: o.relationshipSingle },
              { value: 'partnered', label: o.relationshipPartner },
              { value: 'prefer_not', label: o.relationshipPreferNot },
            ],
          },
          {
            kind: 'single_select',
            id: 'dependents',
            title: o.dependentsTitle,
            mapsTo: 'onboarding.dependents',
            options: [
              { value: 'none', label: o.dependentsNone },
              { value: 'one', label: o.dependentsOne },
              { value: 'two', label: o.dependentsTwo },
              { value: 'three_plus', label: o.dependentsThreeMore },
            ],
          },
          {
            kind: 'single_select',
            id: 'employment_type',
            title: o.employmentTitle,
            mapsTo: 'onboarding.employment',
            options: [
              { value: 'salaried', label: o.employmentSalaried },
              { value: 'self_employed', label: o.employmentSelfEmployed },
              { value: 'gig', label: o.employmentGig },
              { value: 'student', label: o.employmentStudent },
              { value: 'not_working', label: o.employmentNotWorking },
              { value: 'retired', label: o.employmentRetired },
            ],
          },
          {
            kind: 'single_select',
            id: 'base_currency',
            title: o.baseCurrencyTitle,
            mapsTo: 'settings.baseCurrency',
            options: [
              { value: 'AED', label: o.currencyAed },
              { value: 'USD', label: o.currencyUsd },
              { value: 'EGP', label: o.currencyEgp },
              { value: 'EUR', label: o.currencyEur },
              { value: 'GBP', label: o.currencyGbp },
              { value: 'SAR', label: o.currencySar },
            ],
          },
          {
            kind: 'single_select',
            id: 'secondary_currency',
            title: o.secondaryCurrencyTitle,
            mapsTo: 'settings.secondaryCurrency',
            options: [
              { value: 'none', label: o.secondaryCurrencyNone },
              { value: 'AED', label: o.currencyAed },
              { value: 'USD', label: o.currencyUsd },
              { value: 'EGP', label: o.currencyEgp },
              { value: 'EUR', label: o.currencyEur },
              { value: 'GBP', label: o.currencyGbp },
              { value: 'SAR', label: o.currencySar },
            ],
          },
          {
            kind: 'single_select',
            id: 'income_regularity',
            title: o.incomeRegularityTitle,
            mapsTo: 'onboarding.incomeRegularity',
            options: [
              { value: 'stable_monthly', label: o.incomeStable },
              { value: 'variable', label: o.incomeVariable },
              { value: 'irregular', label: o.incomeIrregular },
              { value: 'none', label: o.incomeLittle },
            ],
          },
        ],
      },
      {
        id: 'income_entries',
        type: 'income_entry',
        title: o.incomeEntriesTitle,
        mapsTo: 'onboarding.incomeEntries',
        helpText: o.incomeEntriesHelp,
      },
      {
        id: 'housing_debt_context',
        type: 'field_stack',
        title: o.stackHousingDebtTitle,
        subtitle: o.stackHousingDebtSubtitle,
        helpText: o.stackHousingDebtHelp,
        fields: [
          {
            kind: 'number',
            id: 'housing_monthly',
            title: o.housingTitle,
            placeholder: o.housingPlaceholder,
            mapsTo: 'onboarding.housingMonthly',
            min: 0,
          },
          {
            kind: 'single_select',
            id: 'debt_situation',
            title: o.debtSituationTitle,
            mapsTo: 'onboarding.debtSituation',
            options: [
              { value: 'none', label: o.debtNone },
              { value: 'manageable', label: o.debtSome },
              { value: 'stressful', label: o.debtQuiteBit },
              { value: 'prefer_not', label: o.debtPreferNot },
            ],
          },
        ],
      },
      {
        id: 'debt_entries',
        type: 'debt_entry',
        title: o.debtEntriesTitle,
        mapsTo: 'onboarding.debtEntries',
        helpText: o.debtEntriesHelp,
      },
      {
        id: 'goals_combined',
        type: 'goals_combined',
        title: o.goalsCombinedTitle,
        subtitle: o.goalsCombinedSubtitle,
        helpText: o.goalsCombinedHelp,
        mapsTo: 'financial_goals',
        minSelections: 1,
        maxSelections: 6,
        options: [
          { value: 'emergency_fund', label: o.goalEmergency },
          { value: 'debt_free', label: o.goalDebt },
          { value: 'save_car', label: o.goalCar },
          { value: 'vacation', label: o.goalTravel },
          { value: 'invest', label: o.goalInvest },
          { value: 'home', label: o.goalHome },
          { value: 'education', label: o.goalEducation },
          { value: 'family', label: o.goalFamily },
          { value: 'stable_living', label: o.goalStable },
        ],
      },
      {
        id: 'subs_and_savings',
        type: 'dual_live',
        title: o.dualLiveTitle,
        subtitle: o.dualLiveSubtitle,
        helpText: o.dualLiveHelp,
        subscriptionsTitle: o.subscriptionsTitle,
        savingsTitle: o.savingsDetailTitle,
      },
      {
        id: 'lifestyle_rhythm',
        type: 'field_stack',
        title: o.stackLifestyleTitle,
        subtitle: o.stackLifestyleSubtitle,
        helpText: o.stackLifestyleHelp,
        fields: [
          {
            kind: 'single_select',
            id: 'spending_style',
            title: o.spendingTitle,
            mapsTo: 'onboarding.spendingStyle',
            options: [
              { value: 'frugal', label: o.spendingFrugal },
              { value: 'balanced', label: o.spendingBalanced },
              { value: 'comfortable', label: o.spendingComfortable },
              { value: 'impulsive', label: o.spendingImpulsive },
            ],
          },
          {
            kind: 'single_select',
            id: 'transport_profile',
            title: o.transportTitle,
            mapsTo: 'onboarding.transport',
            options: [
              { value: 'car', label: o.transportCar },
              { value: 'public', label: o.transportPublic },
              { value: 'ride_hail', label: o.transportRideHail },
              { value: 'walk_bike', label: o.transportWalkBike },
              { value: 'mixed', label: o.transportMixed },
            ],
          },
          {
            kind: 'single_select',
            id: 'food_profile',
            title: o.foodTitle,
            mapsTo: 'onboarding.food',
            options: [
              { value: 'cook_home', label: o.foodCookHome },
              { value: 'mix', label: o.foodMix },
              { value: 'eat_out', label: o.foodEatOut },
            ],
          },
          {
            kind: 'single_select',
            id: 'priority_focus',
            title: o.priorityTitle,
            mapsTo: 'onboarding.priorityFocus',
            options: [
              { value: 'save_more', label: o.prioritySave },
              { value: 'debt', label: o.priorityDebt },
              { value: 'reduce_stress', label: o.priorityStress },
              { value: 'enjoy_life', label: o.priorityEnjoy },
            ],
          },
          {
            kind: 'single_select',
            id: 'savings_orientation',
            title: o.savingsOrientationTitle,
            mapsTo: 'onboarding.savingsOrientation',
            options: [
              { value: 'already_save', label: o.savingsAlready },
              { value: 'want_to_start', label: o.savingsWantToStart },
              { value: 'hard_to_save', label: o.savingsHardToSave },
            ],
          },
        ],
      },
      {
        id: 'payment_methods',
        type: 'payment_methods',
        title: o.paymentMethodsTitle,
        subtitle: o.paymentMethodsSubtitle,
        mapsTo: 'onboarding.paymentMethods',
        helpText: o.paymentMethodsHelp,
        closingTitle: o.prePlanTitle,
        closingBody: o.prePlanBody,
        options: [
          { value: 'cash', label: o.paymentCash, methodType: 'cash' },
          { value: 'debit', label: o.paymentDebit, methodType: 'card_debit' },
          { value: 'credit', label: o.paymentCredit, methodType: 'card_credit' },
          { value: 'bank', label: o.paymentBankTransfer, methodType: 'bank_transfer' },
          { value: 'nol', label: o.paymentTransit, methodType: 'nol' },
          { value: 'other', label: o.paymentOther, methodType: 'other' },
        ],
      },
    ],
  }
}
