import type { SurveyConfig } from '@/lib/onboarding/surveyConfig'

/**
 * Expert onboarding: many steps + guided copy. Plan picker runs after `pre_plan`.
 * Keep step `id`s stable — they key `onboardingState.answers` and progress helpers.
 */
export const EXPERT_ONBOARDING_CONFIG: SurveyConfig = {
  steps: [
    {
      id: 'expert_welcome',
      type: 'static',
      title: 'Welcome to Buddget',
      subtitle: 'A guided setup',
      body: 'We’ll ask about your life, money, and goals — then suggest three budget plans you can accept, tweak, or shuffle. None of this is financial advice; it’s a starting point you control.',
      helpText: 'You can revisit this anytime from Profile.',
    },
    {
      id: 'display_name',
      type: 'text',
      title: 'What should we call you?',
      placeholder: 'Your name',
      mapsTo: 'profile.name',
      maxLength: 80,
      helpText: 'Shown in the app header and exports.',
    },
    {
      id: 'country',
      type: 'text',
      title: 'Which country do you live in?',
      placeholder: 'e.g. United Arab Emirates',
      mapsTo: 'profile.country',
      maxLength: 80,
      helpText: 'Used with your city so we can ground cost-of-living context.',
    },
    {
      id: 'city',
      type: 'text',
      title: 'Which city?',
      placeholder: 'e.g. Dubai',
      mapsTo: 'profile.city',
      maxLength: 80,
      helpText: 'We use this to search for typical rent, transport, and food costs in your area.',
    },
    {
      id: 'living_situation',
      type: 'single_select',
      title: 'Your living situation',
      mapsTo: 'onboarding.livingSituation',
      helpText: 'Housing is usually the biggest slice of a budget.',
      options: [
        { value: 'rent_alone', label: 'Renting — on my own' },
        { value: 'rent_roommates', label: 'Renting — with roommates or family' },
        { value: 'own_mortgage', label: 'Own — paying a mortgage' },
        { value: 'own_outright', label: 'Own — no mortgage' },
        { value: 'with_parents', label: 'Living with parents / family (low or no rent)' },
        { value: 'other', label: 'Something else' },
      ],
    },
    {
      id: 'relationship_status',
      type: 'single_select',
      title: 'Relationship status',
      mapsTo: 'onboarding.relationship',
      options: [
        { value: 'single', label: 'Single' },
        { value: 'partnered', label: 'Partnered / married' },
        { value: 'prefer_not', label: 'Prefer not to say' },
      ],
    },
    {
      id: 'dependents',
      type: 'single_select',
      title: 'Children or dependents you support',
      mapsTo: 'onboarding.dependents',
      options: [
        { value: 'none', label: 'None' },
        { value: 'one', label: 'One' },
        { value: 'two', label: 'Two' },
        { value: 'three_plus', label: 'Three or more' },
      ],
    },
    {
      id: 'employment_type',
      type: 'single_select',
      title: 'How do you earn money today?',
      mapsTo: 'onboarding.employment',
      options: [
        { value: 'salaried', label: 'Salaried employee' },
        { value: 'self_employed', label: 'Self-employed / freelance' },
        { value: 'gig', label: 'Gig / part-time mix' },
        { value: 'student', label: 'Student' },
        { value: 'not_working', label: 'Not working right now' },
        { value: 'retired', label: 'Retired' },
      ],
    },
    {
      id: 'base_currency',
      type: 'single_select',
      title: 'Primary currency',
      mapsTo: 'settings.baseCurrency',
      helpText: 'Totals and KPIs use this currency.',
      options: [
        { value: 'AED', label: 'AED — UAE Dirham' },
        { value: 'USD', label: 'USD — US Dollar' },
        { value: 'EGP', label: 'EGP — Egyptian Pound' },
        { value: 'EUR', label: 'EUR — Euro' },
        { value: 'GBP', label: 'GBP — British Pound' },
        { value: 'SAR', label: 'SAR — Saudi Riyal' },
      ],
    },
    {
      id: 'secondary_currency',
      type: 'single_select',
      title: 'Also show amounts in…',
      mapsTo: 'settings.secondaryCurrency',
      options: [
        { value: 'none', label: 'No secondary currency' },
        { value: 'AED', label: 'AED' },
        { value: 'USD', label: 'USD' },
        { value: 'EGP', label: 'EGP' },
        { value: 'EUR', label: 'EUR' },
        { value: 'GBP', label: 'GBP' },
        { value: 'SAR', label: 'SAR' },
      ],
    },
    {
      id: 'income_regularity',
      type: 'single_select',
      title: 'How predictable is your income?',
      mapsTo: 'onboarding.incomeRegularity',
      options: [
        { value: 'stable_monthly', label: 'Stable — similar every month' },
        { value: 'variable', label: 'Variable month to month' },
        { value: 'irregular', label: 'Irregular / project-based' },
        { value: 'none', label: 'Little or no income right now' },
      ],
    },
    {
      id: 'income_entries',
      type: 'income_entry',
      title: 'Your income',
      mapsTo: 'onboarding.incomeEntries',
      helpText: 'Add income the same way you do in the app — or skip and add it later.',
    },
    {
      id: 'housing_monthly',
      type: 'number',
      title: 'Rough monthly housing cost',
      placeholder: 'Rent or mortgage — 0 if none',
      mapsTo: 'onboarding.housingMonthly',
      min: 0,
      helpText: 'Helps the plan respect what you already spend on housing.',
    },
    {
      id: 'debt_situation',
      type: 'single_select',
      title: 'Non-mortgage debt (cards, loans, buy-now-pay-later)',
      mapsTo: 'onboarding.debtSituation',
      options: [
        { value: 'none', label: 'None or minimal' },
        { value: 'manageable', label: 'Some — manageable payments' },
        { value: 'stressful', label: 'Significant — stressful' },
        { value: 'prefer_not', label: 'Prefer not to say' },
      ],
    },
    {
      id: 'debt_entries',
      type: 'debt_entry',
      title: 'Debts you track',
      mapsTo: 'onboarding.debtEntries',
      helpText: 'Add debts like in the app — or skip if you’ll add them later.',
    },
    {
      id: 'financial_goals',
      type: 'multi_select',
      title: 'What are you trying to do with money in the next year?',
      mapsTo: 'onboarding.goals',
      minSelections: 1,
      maxSelections: 6,
      helpText: 'Pick all that matter; we’ll align the suggested split.',
      options: [
        { value: 'emergency_fund', label: 'Build emergency fund' },
        { value: 'debt_free', label: 'Pay down debt faster' },
        { value: 'save_car', label: 'Save for a car' },
        { value: 'vacation', label: 'Vacation / travel' },
        { value: 'invest', label: 'Invest more' },
        { value: 'home', label: 'Save for a home' },
        { value: 'education', label: 'Education / courses' },
        { value: 'family', label: 'Support family / remittance' },
        { value: 'stable_living', label: 'Just keep monthly life stable' },
      ],
    },
    {
      id: 'priority_focus',
      type: 'single_select',
      title: 'If you had to pick one focus for the next 90 days',
      mapsTo: 'onboarding.priorityFocus',
      options: [
        { value: 'save_more', label: 'Save more' },
        { value: 'debt', label: 'Attack debt' },
        { value: 'reduce_stress', label: 'Reduce money stress / stabilize' },
        { value: 'enjoy_life', label: 'Enjoy life while staying responsible' },
      ],
    },
    {
      id: 'spending_style',
      type: 'single_select',
      title: 'Day-to-day spending style',
      mapsTo: 'onboarding.spendingStyle',
      options: [
        { value: 'frugal', label: 'Frugal — I optimize a lot' },
        { value: 'balanced', label: 'Balanced' },
        { value: 'comfortable', label: 'Comfortable — I spend for convenience' },
        { value: 'impulsive', label: 'Impulsive — I want guardrails' },
      ],
    },
    {
      id: 'transport_profile',
      type: 'single_select',
      title: 'Getting around',
      mapsTo: 'onboarding.transport',
      options: [
        { value: 'car', label: 'Own / lease a car' },
        { value: 'public', label: 'Public transit mostly' },
        { value: 'ride_hail', label: 'Ride-hail / taxi mix' },
        { value: 'walk_bike', label: 'Walk / bike' },
        { value: 'mixed', label: 'Mixed' },
      ],
    },
    {
      id: 'food_profile',
      type: 'single_select',
      title: 'Food & dining',
      mapsTo: 'onboarding.food',
      options: [
        { value: 'cook_home', label: 'Mostly cook at home' },
        { value: 'mix', label: 'Mix of home and eating out' },
        { value: 'eat_out', label: 'Eat out / delivery often' },
      ],
    },
    {
      id: 'subscriptions_detail',
      type: 'subscriptions_detail',
      title: 'Subscriptions & recurring',
      mapsTo: 'onboarding.subscriptionsDetail',
      helpText: 'Toggle services, set monthly cost and currency, or add your own.',
    },
    {
      id: 'savings_orientation',
      type: 'single_select',
      title: 'How do you feel about saving today?',
      mapsTo: 'onboarding.savingsOrientation',
      options: [
        { value: 'already_save', label: 'I already save regularly' },
        { value: 'want_to_start', label: 'I want to start / save more' },
        { value: 'hard_to_save', label: 'Hard to save after bills' },
      ],
    },
    {
      id: 'payment_methods',
      type: 'payment_methods',
      title: 'How do you usually pay?',
      subtitle: 'Pick all that apply and add a short nickname',
      mapsTo: 'onboarding.paymentMethods',
      helpText: 'Use “Something else” to add your own — we’ll save it on your profile.',
      options: [
        { value: 'cash', label: 'Cash', methodType: 'cash' },
        { value: 'debit', label: 'Debit card', methodType: 'card_debit' },
        { value: 'credit', label: 'Credit card', methodType: 'card_credit' },
        { value: 'bank', label: 'Bank transfer', methodType: 'bank_transfer' },
        { value: 'nol', label: 'Transit / NOL-style card', methodType: 'nol' },
        { value: 'other', label: 'Something else (you name it)', methodType: 'other' },
      ],
    },
    {
      id: 'pre_plan',
      type: 'static',
      title: 'Ready for your plans',
      body: 'We’ll use your answers plus up-to-date context for your city to suggest three budget mixes. You can accept one as-is, edit amounts, or view the next suggestion — no need to regenerate unless you want to.',
      helpText: 'Takes a few seconds. Requires AI to be configured on the server.',
    },
  ],
}
