import type { SurveyConfig } from '@/lib/onboarding/surveyConfig'

/**
 * Expert onboarding: many steps + guided copy. Plan picker runs after `pre_plan`.
 * Keep step `id`s stable — they key `onboardingState.answers` and progress helpers.
 */
export const EXPERT_ONBOARDING_CONFIG: SurveyConfig = {
  steps: [
    {
      id: 'expert_welcome',
      type: 'static',
      title: 'Welcome to Buddget',
      subtitle: 'Your guided setup',
      body: "Let's take 2 minutes to set up your dashboard. It'll feel like home by the end 🏡",
      helpText: 'You can revisit this anytime from your Profile.',
    },
    {
      id: 'display_name',
      type: 'text',
      title: 'First things first — what should we call you?',
      placeholder: 'Your name',
      mapsTo: 'profile.name',
      maxLength: 80,
      helpText: 'This is just for us — your dashboard will feel more personal with your name on it.',
    },
    {
      id: 'country',
      type: 'text',
      title: 'Where do you call home?',
      placeholder: 'e.g. United Arab Emirates',
      mapsTo: 'profile.country',
      maxLength: 80,
      helpText: 'We use this with your city to understand what life costs where you are.',
    },
    {
      id: 'city',
      type: 'text',
      title: 'And which city?',
      placeholder: 'e.g. Dubai',
      mapsTo: 'profile.city',
      maxLength: 80,
      helpText: 'This helps us find typical rent, transport, and food costs near you.',
    },
    {
      id: 'living_situation',
      type: 'single_select',
      title: "What's your living situation?",
      mapsTo: 'onboarding.livingSituation',
      helpText: 'Housing is usually the biggest part of any budget — good to know yours.',
      options: [
        { value: 'rent_alone', label: 'Renting on my own' },
        { value: 'rent_roommates', label: 'Renting with roommates or family' },
        { value: 'own_mortgage', label: 'Homeowner with a mortgage' },
        { value: 'own_outright', label: 'Homeowner — no mortgage' },
        { value: 'with_parents', label: 'Living with family (little or no rent)' },
        { value: 'other', label: 'Something else' },
      ],
    },
    {
      id: 'relationship_status',
      type: 'single_select',
      title: "What's your relationship status?",
      mapsTo: 'onboarding.relationship',
      options: [
        { value: 'single', label: 'Single' },
        { value: 'partnered', label: 'Partnered / married' },
        { value: 'prefer_not', label: 'Prefer not to say' },
      ],
    },
    {
      id: 'dependents',
      type: 'single_select',
      title: 'Do you support any children or dependents?',
      mapsTo: 'onboarding.dependents',
      options: [
        { value: 'none', label: 'None' },
        { value: 'one', label: 'One' },
        { value: 'two', label: 'Two' },
        { value: 'three_plus', label: 'Three or more' },
      ],
    },
    {
      id: 'employment_type',
      type: 'single_select',
      title: 'How do you earn your money right now?',
      mapsTo: 'onboarding.employment',
      options: [
        { value: 'salaried', label: 'Salaried employee' },
        { value: 'self_employed', label: 'Self-employed / freelance' },
        { value: 'gig', label: 'Gig / part-time mix' },
        { value: 'student', label: 'Student' },
        { value: 'not_working', label: 'Not working right now' },
        { value: 'retired', label: 'Retired' },
      ],
    },
    {
      id: 'base_currency',
      type: 'single_select',
      title: 'Where does most of your money live?',
      mapsTo: 'settings.baseCurrency',
      helpText: 'Pick the currency you earn and spend in most.',
      options: [
        { value: 'AED', label: 'AED — UAE Dirham' },
        { value: 'USD', label: 'USD — US Dollar' },
        { value: 'EGP', label: 'EGP — Egyptian Pound' },
        { value: 'EUR', label: 'EUR — Euro' },
        { value: 'GBP', label: 'GBP — British Pound' },
        { value: 'SAR', label: 'SAR — Saudi Riyal' },
      ],
    },
    {
      id: 'secondary_currency',
      type: 'single_select',
      title: 'Do you manage money in another currency?',
      mapsTo: 'settings.secondaryCurrency',
      helpText: 'Common for expats sending money home. You can always add more later.',
      options: [
        { value: 'none', label: 'Nope, just one currency' },
        { value: 'AED', label: 'AED' },
        { value: 'USD', label: 'USD' },
        { value: 'EGP', label: 'EGP' },
        { value: 'EUR', label: 'EUR' },
        { value: 'GBP', label: 'GBP' },
        { value: 'SAR', label: 'SAR' },
      ],
    },
    {
      id: 'income_regularity',
      type: 'single_select',
      title: 'How predictable is your income right now?',
      mapsTo: 'onboarding.incomeRegularity',
      options: [
        { value: 'stable_monthly', label: 'Stable — pretty similar every month' },
        { value: 'variable', label: 'Variable month to month' },
        { value: 'irregular', label: 'Irregular / project-based' },
        { value: 'none', label: 'Little or no income right now' },
      ],
    },
    {
      id: 'income_entries',
      type: 'income_entry',
      title: "Let's talk income 💵",
      mapsTo: 'onboarding.incomeEntries',
      helpText: "Add your main income source. Don't worry — you can add more or edit these anytime.",
    },
    {
      id: 'housing_monthly',
      type: 'number',
      title: "What's your rough monthly housing cost?",
      placeholder: 'Rent or mortgage — 0 if none',
      mapsTo: 'onboarding.housingMonthly',
      min: 0,
      helpText: 'This helps us build a plan that respects what you already spend on housing.',
    },
    {
      id: 'debt_situation',
      type: 'single_select',
      title: 'Any non-mortgage debt? (cards, loans, buy-now-pay-later)',
      mapsTo: 'onboarding.debtSituation',
      options: [
        { value: 'none', label: 'None or very little' },
        { value: 'manageable', label: "Some — but I'm managing it" },
        { value: 'stressful', label: "Quite a bit — it's stressful" },
        { value: 'prefer_not', label: 'Prefer not to say' },
      ],
    },
    {
      id: 'debt_entries',
      type: 'debt_entry',
      title: 'Got specific debts to track?',
      mapsTo: 'onboarding.debtEntries',
      helpText: 'Add what you owe here, or skip and come back to it later.',
    },
    {
      id: 'financial_goals',
      type: 'multi_select',
      title: 'What do you want your money to do for you this year?',
      mapsTo: 'onboarding.goals',
      minSelections: 1,
      maxSelections: 6,
      helpText: "Pick everything that matters to you — we'll shape your plan around these.",
      options: [
        { value: 'emergency_fund', label: 'Build an emergency fund' },
        { value: 'debt_free', label: 'Pay down debt faster' },
        { value: 'save_car', label: 'Save for a car 🚗' },
        { value: 'vacation', label: 'Travel or vacation ✈️' },
        { value: 'invest', label: 'Start investing (or invest more)' },
        { value: 'home', label: 'Save for a home 🏠' },
        { value: 'education', label: 'Education or courses' },
        { value: 'family', label: 'Support family or send money home' },
        { value: 'stable_living', label: 'Just keep things stable month-to-month' },
      ],
    },
    {
      id: 'priority_focus',
      type: 'single_select',
      title: 'If you had to pick one money focus for the next 90 days…',
      mapsTo: 'onboarding.priorityFocus',
      options: [
        { value: 'save_more', label: 'Save more money' },
        { value: 'debt', label: 'Tackle my debt' },
        { value: 'reduce_stress', label: 'Reduce money stress' },
        { value: 'enjoy_life', label: 'Enjoy life while staying on track' },
      ],
    },
    {
      id: 'spending_style',
      type: 'single_select',
      title: 'How would you describe your spending style?',
      mapsTo: 'onboarding.spendingStyle',
      options: [
        { value: 'frugal', label: 'Frugal — I love a good deal' },
        { value: 'balanced', label: 'Balanced' },
        { value: 'comfortable', label: 'Comfortable — convenience matters to me' },
        { value: 'impulsive', label: 'Impulsive — I could use some guardrails' },
      ],
    },
    {
      id: 'transport_profile',
      type: 'single_select',
      title: 'How do you usually get around?',
      mapsTo: 'onboarding.transport',
      options: [
        { value: 'car', label: 'Own / lease a car' },
        { value: 'public', label: 'Public transit mostly' },
        { value: 'ride_hail', label: 'Ride-hail / taxi mix' },
        { value: 'walk_bike', label: 'Walk / bike' },
        { value: 'mixed', label: 'Mixed' },
      ],
    },
    {
      id: 'food_profile',
      type: 'single_select',
      title: 'What does food look like for you?',
      mapsTo: 'onboarding.food',
      options: [
        { value: 'cook_home', label: 'Mostly cook at home' },
        { value: 'mix', label: 'Mix of home and eating out' },
        { value: 'eat_out', label: 'Eat out / delivery often' },
      ],
    },
    {
      id: 'subscriptions_detail',
      type: 'subscriptions_detail',
      title: 'Your subscriptions & recurring costs',
      mapsTo: 'onboarding.subscriptionsDetail',
      helpText: 'Toggle the services you pay for, set your monthly cost, or add your own.',
    },
    {
      id: 'savings_orientation',
      type: 'single_select',
      title: 'How do you feel about saving right now?',
      mapsTo: 'onboarding.savingsOrientation',
      options: [
        { value: 'already_save', label: "I'm already saving regularly" },
        { value: 'want_to_start', label: 'I want to start saving (or save more)' },
        { value: 'hard_to_save', label: "It's hard to save after bills" },
      ],
    },
    {
      id: 'payment_methods',
      type: 'payment_methods',
      title: 'How do you usually pay?',
      subtitle: 'Pick all that apply — add a nickname so you remember which is which',
      mapsTo: 'onboarding.paymentMethods',
      helpText: `Use “Something else” to add your own — we'll save it to your profile.`,
      options: [
        { value: 'cash', label: 'Cash', methodType: 'cash' },
        { value: 'debit', label: 'Debit card', methodType: 'card_debit' },
        { value: 'credit', label: 'Credit card', methodType: 'card_credit' },
        { value: 'bank', label: 'Bank transfer', methodType: 'bank_transfer' },
        { value: 'nol', label: 'Transit / NOL-style card', methodType: 'nol' },
        { value: 'other', label: 'Something else (you name it!)', methodType: 'other' },
      ],
    },
    {
      id: 'pre_plan',
      type: 'static',
      title: "You're all set! Let's go 🚀",
      body: 'Your dashboard is ready. Start by logging your first expense — it takes 5 seconds.',
      helpText: "Takes a few seconds. We'll build three personalized plans just for you.",
    },
  ],
}
