import { LegalSection } from '@/components/legal/LegalSection'

/** Acceptable Use, AI Disclaimer, and SMS Feature sections for Terms of Service. */
export function TermsUsageSections() {
  return (
    <>
      <LegalSection title="4. Acceptable Use">
        <p>You agree not to use the Service to:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Violate any applicable local, national, or international law or regulation</li>
          <li>Transmit or upload malicious code, viruses, or any software intended to damage or disrupt</li>
          <li>Attempt to gain unauthorized access to any part of the Service or its infrastructure</li>
          <li>Impersonate any person or entity or misrepresent your affiliation with any person or entity</li>
          <li>Harvest, scrape, or collect data from the Service using automated means without permission</li>
          <li>Use the Service for commercial data resale, competitive intelligence, or similar purposes</li>
          <li>Interfere with or disrupt the integrity or performance of the Service</li>
        </ul>
        <p>
          We reserve the right to investigate violations and take appropriate action, including suspending or
          terminating accounts and reporting to law enforcement authorities.
        </p>
      </LegalSection>

      <LegalSection title="5. AI Features — Not Financial Advice">
        <p>
          Buddget includes AI-assisted features powered by Google Gemini, including budget plan generation,
          spending analysis, and an AI chat assistant (&ldquo;Buddgy&rdquo;). These features are provided for
          informational and organizational purposes only.
        </p>
        <p className="font-medium text-[var(--color-brand-text-primary)]">
          Nothing generated by the AI — including budget suggestions, savings recommendations, or spending
          analysis — constitutes financial, investment, tax, accounting, or legal advice. AI outputs may
          contain errors, omissions, or information that is not appropriate for your specific circumstances.
        </p>
        <p>
          You should consult a qualified licensed financial professional before making any significant
          financial decisions. Buddget expressly disclaims any liability arising from your reliance on
          AI-generated outputs.
        </p>
      </LegalSection>

      <LegalSection title="6. SMS Auto-Tracking Feature">
        <p>
          Buddget offers an optional SMS auto-tracking feature that allows you to forward bank notification
          SMS messages to the Service via an iOS Shortcut or Android Bridge application. By enabling this
          feature:
        </p>
        <ul className="list-disc pl-5 space-y-1">
          <li>
            You consent to transmitting the raw text content of bank SMS messages (including transaction
            amounts, merchant names, and account references) to Buddget&apos;s servers for parsing and
            expense logging.
          </li>
          <li>
            You confirm that you are the authorized recipient of the SMS messages you forward and that
            forwarding such messages complies with all applicable laws in your jurisdiction.
          </li>
          <li>
            You understand that SMS content may contain sensitive financial information and is transmitted
            over HTTPS and stored in your Buddget account.
          </li>
          <li>
            You may revoke access at any time by disabling the feature and rotating or deactivating your
            SMS ingest token in Settings.
          </li>
        </ul>
        <p>
          The SMS feature currently supports selected Egyptian bank SMS formats. We make no guarantee of
          parsing accuracy and are not responsible for any expense logging errors arising from unrecognized
          SMS formats.
        </p>
      </LegalSection>
    </>
  )
}
