import { LegalSection } from '@/components/legal/LegalSection'

/** Sections 4–7: Acceptable Use, AI Disclaimer, Native Device Features, SMS Auto-Tracking. */
export function TermsUsageSections() {
  return (
    <>
      <LegalSection title="4. Acceptable Use">
        <p>You agree not to use the Service to:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Violate any applicable local, national, or international law or regulation</li>
          <li>Transmit or upload malicious code, viruses, or software intended to disrupt or damage</li>
          <li>Attempt to gain unauthorized access to any part of the Service or its infrastructure</li>
          <li>
            Impersonate any person or entity or misrepresent your affiliation with any person or entity
          </li>
          <li>
            Harvest, scrape, or collect data from the Service using automated means without express
            permission
          </li>
          <li>
            Use the Service for commercial data resale, competitive intelligence, or similar purposes
          </li>
          <li>Interfere with or disrupt the integrity or performance of the Service</li>
        </ul>
        <p>
          We reserve the right to investigate violations and take appropriate action, including
          suspending or terminating accounts.
        </p>
      </LegalSection>

      <LegalSection title="5. AI Features — Not Financial Advice">
        <p>
          Buddget includes AI-assisted features including budget plan generation, spending analysis,
          voice expense parsing, and an AI chat assistant. These features are provided for informational
          and organizational purposes only and are powered by third-party AI services including Google
          Gemini.
        </p>
        <p className="font-medium text-[var(--color-brand-text-primary)]">
          Nothing generated by the AI — including budget suggestions, savings recommendations, spending
          analysis, or expense categorization — constitutes financial, investment, tax, accounting, or
          legal advice. AI outputs may contain errors, omissions, or information that is not appropriate
          for your specific financial circumstances.
        </p>
        <p>
          You should consult a qualified licensed financial professional before making any significant
          financial decisions. We expressly disclaim any liability arising from your reliance on
          AI-generated outputs.
        </p>
      </LegalSection>

      <LegalSection title="6. Optional Native Device Features">
        <p>
          When using Buddget as a native application (iOS or Android), you may be asked to grant
          permission for the following device features. All such permissions are optional and can be
          revoked at any time through your device settings:
        </p>
        <p>
          <strong className="text-[var(--color-brand-text-primary)]">Microphone:</strong> Used solely to
          capture voice input for expense logging. Audio is processed on our servers for transcription
          and is not retained after the expense is logged.
        </p>
        <p>
          <strong className="text-[var(--color-brand-text-primary)]">Camera:</strong> Used solely to
          photograph receipts for automatic expense extraction. Images are sent to our servers for
          analysis and are not permanently stored after processing.
        </p>
        <p>
          <strong className="text-[var(--color-brand-text-primary)]">Biometric authentication:</strong>{' '}
          Face ID or fingerprint data is processed entirely by your device&apos;s operating system (iOS
          Secure Enclave or Android TEE). Biometric data is never transmitted to or stored on our
          servers.
        </p>
        <p>
          <strong className="text-[var(--color-brand-text-primary)]">Push notifications:</strong> Used
          to alert you to budget milestones, debt reminders, and transaction confirmations. Push tokens
          are stored to enable delivery and can be revoked by disabling notifications in device settings.
        </p>
      </LegalSection>

      <LegalSection title="7. SMS Auto-Tracking Feature">
        <p>
          Buddget offers an optional SMS auto-tracking feature that enables automatic expense detection
          from bank notification SMS messages via an iOS Shortcut or Android background service. This
          feature is strictly opt-in, disabled by default, and requires your explicit activation in
          Settings.
        </p>
        <p>By enabling this feature, you:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li>
            Consent to transmitting the text content of bank notification SMS messages to Buddget&apos;s
            servers for AI-powered parsing and expense logging
          </li>
          <li>
            Confirm that you are the authorized recipient of the SMS messages you forward and that doing
            so complies with all applicable laws in your jurisdiction
          </li>
          <li>
            Understand that SMS content may contain sensitive financial information and is transmitted
            over encrypted HTTPS connections
          </li>
          <li>
            Acknowledge that only extracted expense data (amount, merchant, date, category) is saved to
            your account — raw SMS text is not permanently stored after processing
          </li>
          <li>
            Understand that parsing accuracy varies by bank and message format, and that we do not
            guarantee correct categorization of all transactions
          </li>
        </ul>
        <p>
          This feature currently supports common bank SMS formats from Egypt, UAE, Saudi Arabia, and
          Kuwait. Additional formats are added over time.
        </p>
        <p>
          You may disable SMS auto-tracking and revoke your SMS ingest token at any time via Settings
          &rarr; Integrations &rarr; SMS Tracking.
        </p>
        <p>
          To prevent duplicate logging, our system compares incoming SMS-derived transactions against
          recent entries. Where duplicates are detected, only one entry is recorded.
        </p>
      </LegalSection>
    </>
  )
}
